
# logging file
logging:
    file: logs/test-service.log

server:
    port: 8080

spring:

    output:
        ansi:
            enabled: always
    jpa:
        database: postgresql
        #database-platform: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://192.168.8.66:5432/test
        username: test
        password: test

    redis:
        host: redis地址
        #端口号
        port: 6379
        #如果有密码
        password: redis
        #客户端超时时间单位是毫秒 默认是2000
        #redis.timeout=10000
        #数据库编号
        dataBase: 0
        #最大空闲数
        maxIdle: 300
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
        #redis.maxActive=600
        #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        maxTotal: 1000
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        maxWaitMillis: 1000
        #连接的最小空闲时间 默认1800000毫秒(30分钟)
        minEvictableIdleTimeMillis: 300000
        #每次释放连接的最大数目,默认3
        numTestsPerEvictionRun: 1024
        #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
        timeBetweenEvictionRunsMillis: 30000
        #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
        testOnBorrow: true
        #在空闲时检查有效性, 默认false
        testWhileIdle: true
        ssl: false

